// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RabbitMqService.DataAccess;

#nullable disable

namespace RabbitMqService.DataAccess.Migrations
{
    [DbContext(typeof(MessageDbContext))]
    [Migration("20241028143801_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.AttributeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreditPartEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DebitPartEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MessageEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreditPartEntityId");

                    b.HasIndex("DebitPartEntityId");

                    b.HasIndex("MessageEntityId");

                    b.ToTable("AttributeEntity");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.CreditPartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgreementNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CreditPartEntity");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.DebitPartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgreementNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DebitPartEntity");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.DocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DocumentEntity");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankingDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreditPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DebitPartId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreditPartId");

                    b.HasIndex("DebitPartId");

                    b.HasIndex("RequestId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.RequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("RequestEntity");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.AttributeEntity", b =>
                {
                    b.HasOne("RabbitMqService.DataAccess.Entities.CreditPartEntity", null)
                        .WithMany("Attributes")
                        .HasForeignKey("CreditPartEntityId");

                    b.HasOne("RabbitMqService.DataAccess.Entities.DebitPartEntity", null)
                        .WithMany("Attributes")
                        .HasForeignKey("DebitPartEntityId");

                    b.HasOne("RabbitMqService.DataAccess.Entities.MessageEntity", null)
                        .WithMany("Attributes")
                        .HasForeignKey("MessageEntityId");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.MessageEntity", b =>
                {
                    b.HasOne("RabbitMqService.DataAccess.Entities.CreditPartEntity", "CreditPart")
                        .WithMany()
                        .HasForeignKey("CreditPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RabbitMqService.DataAccess.Entities.DebitPartEntity", "DebitPart")
                        .WithMany()
                        .HasForeignKey("DebitPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RabbitMqService.DataAccess.Entities.RequestEntity", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditPart");

                    b.Navigation("DebitPart");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.RequestEntity", b =>
                {
                    b.HasOne("RabbitMqService.DataAccess.Entities.DocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.CreditPartEntity", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.DebitPartEntity", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("RabbitMqService.DataAccess.Entities.MessageEntity", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
